#!/usr/bin/env python3
"""Turn a tunables config file into the header sim/tunables.h applies to the build's defaults.

    tunables_cfg.py <tunables.def> <config> <out.h>

The config holds one `Name = value` per line; `#` starts a comment. `Name` is a row of
tunables.def, spelled as there. `value` is a decimal literal of the row's type (`0.25`, `4`,
`1e-6`), or `0x...`, the value's raw bits (for a float, the float's 32 bits). A name the table
does not hold, a name given twice, or a value that is not a number of the row's type stops the
build. The range check is the compiler's: tunables.h asserts every default inside its row's
[min, max], and the override is a default.

The output is the same for the same config, so a rebuild with an unchanged config is the same
binary. Only sim/build.sh calls this, and only when ONI_TUNABLES_CFG is set.
"""
import re
import sys

ROW = re.compile(r'^\s*TUNABLE(_AT)?\(\s*(\w+)\s*,\s*(\w+)\s*,\s*(?:(\d+)\s*,\s*)?(\w+)\s*,', re.M)


def rows(def_text):
    out = {}
    for at, name, field, index, typ in ROW.findall(def_text):
        member = f"{field}[{index}]" if at else field
        out[name] = (member, typ)
    return out


def literal(typ, value, where):
    v = value.strip()
    if re.fullmatch(r'0[xX][0-9a-fA-F]+', v):
        return f"oni_sim::tunables_detail::Bits<{typ}>::From({v}ULL)"
    if typ == 'int32_t':
        if not re.fullmatch(r'[+-]?\d+', v):
            sys.exit(f"{where}: {v!r} is not an integer")
        return f"static_cast<int32_t>({v})"
    if not re.fullmatch(r'[+-]?(\d+\.?\d*|\.\d+)([eE][+-]?\d+)?', v):
        sys.exit(f"{where}: {v!r} is not a decimal number")
    # `20000f` is not a C++ literal; a float needs a point or an exponent before its suffix.
    if typ == 'float' and re.fullmatch(r'[+-]?\d+', v):
        v += '.0'
    return f"{v}f" if typ == 'float' else f"static_cast<double>({v})"


def main():
    def_path, cfg_path, out_path = sys.argv[1:4]
    table = rows(open(def_path).read())
    seen = {}
    pairs = []
    for n, raw in enumerate(open(cfg_path), 1):
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        where = f"{cfg_path}:{n}"
        if '=' not in line:
            sys.exit(f"{where}: expected `Name = value`")
        name, value = (p.strip() for p in line.split('=', 1))
        if name not in table:
            sys.exit(f"{where}: {name!r} is not a row of tunables.def")
        if name in seen:
            sys.exit(f"{where}: {name} is already set at line {seen[name]}")
        seen[name] = n
        member, typ = table[name]
        pairs.append(f"  X({member}, {literal(typ, value, where)})")
    with open(out_path, 'w') as f:
        f.write("// GENERATED by sim/tunables_cfg.py from %s. Do not edit.\n" % cfg_path)
        f.write("#pragma once\n#define ONI_TUNABLE_OVERRIDES(X) \\\n")
        f.write(" \\\n".join(pairs) if pairs else "  /* no rows */")
        f.write("\n")
    print(f"tunables override: {len(pairs)} row(s) from {cfg_path}")


main()
